import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import { FooterComp } from "@/components/FooterComp";
import { Header } from "@/components/Header";
import { Metadata } from "next";
import localFont from "next/font/local";
import UserDetailProvider from "@/provider/UserDetailProvider";
import MongoUserProvider from "@/provider/MongoUserProvider";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Find Worker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <ClerkProvider>
          <UserDetailProvider>
            <MongoUserProvider>
              <div className="flex flex-col min-h-screen">
                <Header />
                <main className="flex-1">{children}</main>
                <FooterComp />
              </div>
              <Toaster />
            </MongoUserProvider>
          </UserDetailProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
